
name: CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

  workflow_dispatch:

jobs:


  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Tests
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
