name: PR Check
on:
  pull_request:
    branches:
      - main
      - releases/*
    types: [ opened, reopened, edited, synchronize ]

jobs:
  check-pr:
    uses: ./.github/workflows/.reusable-common-pr-check.yaml
    permissions:
      pull-requests: write
