name: PR Check
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, reopened, edited, synchronize ]
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
