name: PR Check
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, reopened, edited, synchronize ]
  push:
    branches:
      - 'main'

jobs:
  # TODO: remove check-pr job once template no longer enforces job.
  check-pr:
    uses: ./.github/workflows/.common-pr-check.yml
    permissions:
      pull-requests: write
  
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
