name: PR Check
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [ opened, reopened, edited, synchronize ]

jobs:
  check-pr:
    uses: ./.github/workflows/.common-pr-check.yml
    permissions:
      pull-requests: write
