name: PR Check
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, reopened, edited, synchronize ]

jobs:

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  policy-check:
      uses: ./.github/workflows/policy-check.yml
      permissions:
          pull-requests: write
